question_data = [
{"category": "Animals", "type": "multiple", "difficulty": "medium",
 "question": "What type of animal is a natterjack?", "correct_answer": "Toad",
 "incorrect_answers": ["Bird", "Fish", "Insect"]},
{"category": "Geography", "type": "boolean", "difficulty": "easy",
 "question": "There is a city called Rome in every continent on Earth.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"category": "History", "type": "multiple", "difficulty": "hard",
 "question": "When was the SS or Schutzstaffel established?",
 "correct_answer": "April 4th, 1925",
 "incorrect_answers": ["September 1st, 1941", "March 8th, 1935",
                       "February 21st, 1926"]},
{"category": "Entertainment: Television", "type": "multiple", "difficulty": "easy",
 "question": "Guy&#039;s Grocery Games is hosted by which presenter?",
 "correct_answer": "Guy Fieri",
 "incorrect_answers": ["Guy Martin", "Guy Ritchie", "Ainsley Harriott"]},
{"category": "Entertainment: Comics", "type": "multiple", "difficulty": "medium",
 "question": "In &quot;Sonic the Hedgehog&quot; comic, who was the creator of Roboticizer? ",
 "correct_answer": "Professor Charles the Hedgehog",
 "incorrect_answers": ["Julian Robotnik", "Ivo Robotnik", "Snively Robotnik"]},
{"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
 "question": "Who recorded the album called &quot;Down to the Moon&quot; in 1986?",
 "correct_answer": "Andreas Vollenweider",
 "incorrect_answers": ["Jean-Michel Jarre", "Bing Crosby", "Enya"]},
{"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
 "question": "In the Half-Life franchise, what is the real name of the &quot;gravity gun&quot;?",
 "correct_answer": "Zero-Point Energy Field Manipulator",
 "incorrect_answers": ["Universal Gravity Manipulation Device",
                       "Isaac Newton&#039;s Theory Disprover",
                       "Quantum Energy Displacement Modifier"]},
{"category": "Geography", "type": "multiple", "difficulty": "hard",
 "question": "What is the name of the Canadian national anthem?",
 "correct_answer": "O Canada",
 "incorrect_answers": ["O Red Maple", "Leaf-Spangled Banner",
                       "March of the Puck Drop"]},
{"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
 "question": "What programming language was used to create the game &quot;Minecraft&quot;?",
 "correct_answer": "Java", "incorrect_answers": ["HTML 5", "C++", "Python"]},
{"category": "Entertainment: Television", "type": "multiple", "difficulty": "medium",
 "question": "Which WWF wrestler had the nickname &quot;The Ayatollah of Rock &#039;N&#039; Rolla&quot;?",
 "correct_answer": "Chris Jericho",
 "incorrect_answers": ["Marty Jannetty", "Scott Hall", "Shawn Michaels"]}
]
